# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB8MF9Kp3kU_CwKf02-R_oJViyQJIg2y
"""

!pip install pymupdf pytesseract pillow
!apt-get install -y poppler-utils tesseract-ocr

import fitz
import pytesseract
from PIL import Image
import io

def extract_text_from_pdf(pdf_file):
  text = ""
  with fitz.open(pdf_file) as doc:
    for page_num, page in enumerate(doc):
      page_text = page.get_text()

      if page_text.strip():
        text += page_text
      else:
        pix = page.get_pixmap(dpi = 200)
        img = Image.open(io.BytesIO(pix.tobytes(output = "png")))
        img = img.convert("RGB")
        ocr_text = pytesseract.image_to_string(img)
        text += ocr_text
  return text

pdf_text = extract_text_from_pdf("/content/sample_data/toaz.info-ansi-c-balaguruswamy-c-languagepdf-pr_21797c4598cda0df541d1b270f539c08.pdf")

from datasets import Dataset
import re

chunks = [pdf_text[i:i+1000] for i in range(0, len(pdf_text), 1000)]
data = []
for i, chunk in enumerate(chunks):
  data.append({
      "instruction": f"Summarize this textbook content (part {i+1})",
        "output": chunk
  })
print(pdf_text)
dataset = Dataset.from_list(data)
print(dataset[:100])

!pip install accelerate peft bitsandbytes

!pip install --upgrade transformers bitsandbytes

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from huggingface_hub import login
login(new_session=False)
model_name = "google/gemma-2b"
tokenizer = AutoTokenizer.from_pretrained(model_name)
quantization_config = BitsAndBytesConfig(load_in_4bit = True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map = "auto"
)

from peft import LoraConfig, get_peft_model
from transformers import TrainingArguments, Trainer

lora_config = LoraConfig(
    r = 16,
    lora_alpha = 32,
    target_modules = ['q_proj', 'v_proj'],
    lora_dropout = 0.05,
    bias = 'none',
    task_type = "CAUSAL_LM",
)

model = get_peft_model(model, lora_config)

training_args = TrainingArguments(
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 4,
    num_train_epochs = 1,
    learning_rate = 2e-4,
    fp16 = True,
    logging_steps = 10,
    output_dir = "./results"
)

from transformers import DataCollatorForLanguageModeling

def format_data(example):
  tokenized = tokenizer(
        f"### Instruction: {example['instruction']}\n### Response: {example['output']}",
        truncation=True,
        padding="max_length",
        max_length=512
    )
    # Add labels (usually same as input_ids for causal LM)
  tokenized["labels"] = tokenized["input_ids"].copy()
  return tokenized
print(len(dataset))
dataset = dataset.map(format_data)
print(dataset.column_names)

dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
trainer = Trainer(
    model = model,
    train_dataset = dataset,
    args = training_args,
    data_collator = DataCollatorForLanguageModeling(tokenizer, mlm = False),
)
trainer.train()

from transformers import pipeline
pipe = pipeline("text-generation",model = model, tokenizer = tokenizer)

print(pipe(
    "### Question:\nWhat is main() function?\n### Answer:\n",
    max_new_tokens=150,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])

print(pipe(
    "### Question:\nWhat is printf()?\n### Answer:\n",
    max_new_tokens=150,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])

print(pipe(
    "### Question:\nWhat is America?\n### Answer:\n",
    max_new_tokens=150,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])

print(pipe(
    "### Question:\nWhat is #define?\n### Answer:\n",
    max_new_tokens=150,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])
