# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-B0SftYdcX0nnt3TmEFL5gqr91ClEfu
"""

!pip install pymupdf pytesseract pillow
!apt-get install -y poppler-utils tesseract-ocr

import fitz  # PyMuPDF
import pytesseract
from PIL import Image
import io

def extract_text_from_pdf(pdf_file):
    text = ""
    with fitz.open(pdf_file) as doc:
        for page_num, page in enumerate(doc):
            # Get digital text first
            page_text = page.get_text("text").strip()

            # Always extract images too (for mixed PDFs)
            images_text = ""
            for img_index, img in enumerate(page.get_images(full=True)):
                xref = img[0]
                pix = fitz.Pixmap(doc, xref)

                if pix.n < 5:  # GRAY or RGB
                    pil_img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
                else:  # CMYK
                    pix = fitz.Pixmap(fitz.csRGB, pix)
                    pil_img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

                ocr_text = pytesseract.image_to_string(pil_img)
                images_text += "\n" + ocr_text
                pix = None  # free memory

            # If no text at all, OCR the whole page
            if not page_text:
                pix = page.get_pixmap(dpi=300)  # high quality for OCR
                pil_img = Image.open(io.BytesIO(pix.tobytes("png"))).convert("RGB")
                page_text = pytesseract.image_to_string(pil_img)

            # Merge text + OCR-extracted text
            text += f"\n--- Page {page_num+1} ---\n" + page_text + images_text

    return text

pdf_text_1 = extract_text_from_pdf("/content/sample_data/Introduction_to_Python_Programming_-_WEB.pdf")
pdf_text_2 = extract_text_from_pdf("/content/sample_data/toaz.info-ansi-c-balaguruswamy-c-languagepdf-pr_21797c4598cda0df541d1b270f539c08.pdf")

from datasets import Dataset
import re

chunks_1 = [pdf_text_1[i:i+1000] for i in range(0, len(pdf_text_1), 1000)]
data_1 = []
for i, chunk in enumerate(chunks_1):
  data_1.append({
      "instruction": f"Summarize this textbook content (part {i+1})",
        "output": chunk
  })
print(pdf_text_1)
dataset_1 = Dataset.from_list(data_1)
print(dataset_1[:100])

from datasets import Dataset
import re

chunks_2 = [pdf_text_2[i:i+1000] for i in range(0, len(pdf_text_2), 1000)]
data_2 = []
for i, chunk in enumerate(chunks_2):
  data_2.append({
      "instruction": f"Summarize this textbook content (part {i+1})",
        "output": chunk
  })
print(pdf_text_2)
dataset_2 = Dataset.from_list(data_2)
print(dataset_2[:100])

!pip install accelerate peft bitsandbytes

!pip install --upgrade transformers bitsandbytes

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from huggingface_hub import login
login(new_session=False)
model_name = "google/gemma-2b"
tokenizer = AutoTokenizer.from_pretrained(model_name)
quantization_config = BitsAndBytesConfig(load_in_4bit = True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map = "auto"
)

from peft import LoraConfig, get_peft_model
from transformers import TrainingArguments, Trainer

lora_config = LoraConfig(
    r = 16,
    lora_alpha = 32,
    target_modules = ['q_proj', 'v_proj'],
    lora_dropout = 0.05,
    bias = 'none',
    task_type = "CAUSAL_LM",
)

model = get_peft_model(model, lora_config)

training_args = TrainingArguments(
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 4,
    num_train_epochs = 1,
    learning_rate = 2e-4,
    fp16 = True,
    logging_steps = 10,
    output_dir = "./results"
)

from transformers import DataCollatorForLanguageModeling

def format_data(example):
  tokenized = tokenizer(
        f"### Instruction: {example['instruction']}\n### Response: {example['output']}",
        truncation=True,
        padding="max_length",
        max_length=512
    )
    # Add labels (usually same as input_ids for causal LM)
  tokenized["labels"] = tokenized["input_ids"].copy()
  return tokenized
print(len(dataset_1))
dataset_1 = dataset_1.map(format_data)
print(dataset_1.column_names)

dataset_1.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
trainer_1 = Trainer(
    model = model,
    train_dataset = dataset_1,
    args = training_args,
    data_collator = DataCollatorForLanguageModeling(tokenizer, mlm = False),
)
trainer_1.train()

from transformers import DataCollatorForLanguageModeling

def format_data(example):
  tokenized = tokenizer(
        f"### Instruction: {example['instruction']}\n### Response: {example['output']}",
        truncation=True,
        padding="max_length",
        max_length=512
    )
    # Add labels (usually same as input_ids for causal LM)
  tokenized["labels"] = tokenized["input_ids"].copy()
  return tokenized
print(len(dataset_2))
dataset_2 = dataset_2.map(format_data)
print(dataset_2.column_names)

dataset_2.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
trainer_2 = Trainer(
    model = model,
    train_dataset = dataset_2,
    args = training_args,
    data_collator = DataCollatorForLanguageModeling(tokenizer, mlm = False),
)
trainer_2.train()

from transformers import pipeline
pipe = pipeline("text-generation",model = model, tokenizer = tokenizer)

print(pipe(
    "### Question:\nWhat is printf()?\n### Answer:\n",
    max_new_tokens=150,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])

print(pipe(
    "### Question:\nWhat is print?\n### Answer:\n",
    max_new_tokens=150,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])

print(pipe(
    "### Question:\nHow to find prime number using c?\n### Answer:\n",
    max_new_tokens=150,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])

print(pipe(
    "### Question:\nHow to print fibonacci series in python?\n### Answer:\n",
    max_new_tokens=350,
    do_sample=True,
    top_p=0.9,
    temperature=0.7,
    repetition_penalty=1.2,
    eos_token_id=tokenizer.eos_token_id  # stop when EOS is hit
)[0]['generated_text'])